steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - script: |
      . build_dotnet.sh
    displayName: 'Build dotnet'
  - script: |
      . build_frontend.sh
    displayName: 'Build frontend'
  - script: |
      . build_release_to_github.sh
    displayName: 'Push release to github'
variables:
  - name: RELEASE_BRANCH
    value: $(Build.SourceBranchName)
  - name: COMPLETE_RELEASE_BRANCH
    value: $(Build.SourceBranch)
  - name: GIT_COMMIT_SHA
    value: $(Build.SourceVersion)
  - group: "Github-Token"
trigger:
  - master
pool:
  vmImage: 'ubuntu-16.04'