steps:
  - script: |
      . build_dockerfile.sh
    displayName: 'Build docker image'
  - script: |
      . build_nuget.sh
    displayName: 'Build NuGet package'
variables:
  - name: RELEASE_BRANCH
    value: $(Build.SourceBranchName)
  - name: COMPLETE_RELEASE_BRANCH
    value: $(Build.SourceBranch)
  - name: GIT_COMMIT_SHA
    value: $(Build.SourceVersion)
trigger:
  - master
pool:
  vmImage: 'ubuntu-16.04'